############################################
# 1) Frontend build (Angular)
############################################
FROM node:24.16-alpine3.23 AS fe

WORKDIR /builder

COPY package*.json ./
RUN npm ci --legacy-peer-deps --ignore-scripts

COPY . .
ARG BASE_PATH=/
RUN npx ng build --base-href=${BASE_PATH}


############################################
# 2) Backend build (Rust API — musl/static)
############################################
FROM rust:1.96.0-alpine3.23 AS be

WORKDIR /builder

RUN apk add --no-cache \
    build-base \
    pkgconfig \
    openssl-dev \
    openssl-libs-static

COPY api ./api

WORKDIR /builder/api

RUN cargo build --release


############################################
# 3) Runtime image (Alpine + debug tools, non-root, OpenShift-friendly)
############################################
FROM alpine:3.23.4

RUN apk update && apk upgrade --no-cache \
    && apk add --no-cache \
        ca-certificates \
        tzdata \
        bash \
        curl \
        wget \
        procps \
        net-tools \
        bind-tools \
        strace \
        lsof \
    && apk add --no-cache --upgrade \
        libcurl \
        busybox \
        busybox-binsh \
        ssl_client

# Create non-root user
RUN addgroup -S app && adduser -S -G app app

WORKDIR /app

ARG VERSION_ARG=0.0.4
ENV VERSION=${VERSION_ARG}
ENV RUST_LOG=debug

# Copy frontend and backend artifacts
COPY --from=fe /builder/dist/gitlab-ci-dashboard/browser ./spa
COPY --from=be /builder/api/target/release/gcd_api ./gcd_api

# Fix permissions
RUN chown -R app:app /app

USER app

EXPOSE 8080

ENTRYPOINT ["/app/gcd_api"]