FROM node:24.11.1-alpine AS fe
WORKDIR /builder
COPY package*.json ./
RUN npm ci --legacy-peer-deps --ignore-scripts
COPY . .
RUN npm run build

# 2) Backend build (Rust API)
FROM rust:alpine3.22 AS be
WORKDIR /builder
RUN apk add --no-cache \
    build-base \
    pkgconfig \
    openssl-dev \
    openssl-libs-static
COPY api ./api
WORKDIR /builder/api
RUN cargo build --release

# 3) Runtime image (Alpine, non-root, OpenShift-friendly)
FROM docker.io/mohankrishna999/alpine:3.23.0
RUN apk add --no-cache \
    ca-certificates \
    tzdata
RUN addgroup -S app && adduser -S -G app app
WORKDIR /app
ARG VERSION_ARG=0.0.1
ENV VERSION=${VERSION_ARG}
ENV RUST_LOG=info
COPY --from=fe /builder/dist/gitlab-ci-dashboard/browser ./spa
COPY --from=be /builder/api/target/release/gcd_api ./gcd_api
RUN chown -R app:app /app
USER app
EXPOSE 8080
ENTRYPOINT ["/app/gcd_api"]

